### ISSUE TITLE
cron job fails with "DB Error: Duplicate entry '1' for key 'PRIMARY'"

### ISSUE THREAD

**Issue by pbchase** [ctsit/report_production_candidates#16]
We had a fatal error from this module's cron job:

```From: <xxx@example.org>
Subject: External Module Exception in Cron Job 
Date: March 10, 2019 at 2:28:02 PM EDT
To: <xxx@example.org>, ..., <xxx@example.org>
Reply-To: <xxx@example.org>

[This message was automatically generated by REDCap]

Cron job "report_production_candidates_cron" failed for External Module "report_production_candidates" with the following Exception: Exception: Error running External Module query: 
DB Error: Duplicate entry '1' for key 'PRIMARY'
SQL: INSERT INTO redcap_project_stats (project_id) select project_id from redcap_projects in /var/www.backup/redcap-20190307T2035/redcap_v8.11.2/ExternalModules/classes/ExternalModules.php:1245
Stack trace:
#0 /var/www.backup/redcap-20190307T2035/modules/report_production_candidates_v1.0.2/ExternalModule.php(62): ExternalModules\ExternalModules::query('INSERT INTO red...')
#1 /var/www.backup/redcap-20190307T2035/modules/report_production_candidates_v1.0.2/ExternalModule.php(109): ReportProductionCandidatesModule\ExternalModule\ExternalModule->add_rows_to_stats_table()
#2 /var/www.backup/redcap-20190307T2035/modules/report_production_candidates_v1.0.2/ExternalModule.php(22): ReportProductionCandidatesModule\ExternalModule\ExternalModule->update_stats_table()
#3 /var/www.backup/redcap-20190307T2035/redcap_v8.11.2/ExternalModules/classes/ExternalModules.php(3227): ReportProductionCandidatesModule\ExternalModule\ExternalModule->report_production_candidates_cron(Array)
#4 /var/www.backup/redcap-20190307T2035/redcap_v8.11.2/Classes/Cron.php(295): ExternalModules\ExternalModules::callCronMethod('7', 'report_producti...')
#5 /var/www.backup/redcap-20190307T2035/redcap_v8.11.2/cron.php(22): Cron->execute()
#6 /var/www.backup/redcap-20190307T2035/cron.php(11): include('/var/www.backup...')
#7 {main}

URL: http://
Server: redcap.example.org (redcap.example.org)
Module Name: Report Production Candidates (report_production_candidates)
Module Author(s): ...
Hook Run Time: 1 seconds
```
This is probably not the _first_ run of the cron job since the upgrade to PHP 7.2 and the REDCap 8.11.2, but it is one of the first.

**Comment by pbchase** [comment]
A more in-depth review of the logs shows this error started on the first run after the upgrade to PHP 7.2 and the REDCap 8.11.2. This is likely a PHP 7.2 error. A RC 8.11.2 error is possible, but less likely.

**Comment by pbchase** [comment]
@marlycormar, this is all fixed now, right? If so, please close this issue.

**Comment by marlycormar** [comment]
@pbchase, yes. The issue was fixed after I removed the duplicate cron job calls.
